name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日凌晨运行
  workflow_dispatch:    # 支持手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with latest blog posts
        id: update_blog
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.moontung.top/index.xml"
          max_post_count: "4"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Update README with latest blog posts"
          else
            echo "No changes detected. Skipping."
            exit 0
          fi

      - name: Push changes
        env:
          SHEETUNG_UPDATE_TOKEN: ${{ secrets.SHEETUNG_UPDATE_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${SHEETUNG_UPDATE_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD
